# Generated by Django 5.0.2 on 2024-11-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_rename_event_name_participant_participant_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='participant_event_name',
            new_name='event_name',
        ),
    ]
