# Generated by Django 5.0.2 on 2024-11-22 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_rename_participant_event_name_participant_event_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date', 'start_time'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['participant_name'], 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='event_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='eventapp.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_email',
            field=models.EmailField(max_length=100),
        ),
    ]
